version: '2'
services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper-ri
    ports:
      - "2181:2181"
  kafka1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: "INTERNAL://kafka1:19091, EXTERNAL://:9091"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:19091, EXTERNAL://localhost:9091"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka1
      - zookeeper
      - schema-registry1
    ports:
      - "8083:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19091
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry1:8085

  schema-registry1:
    image: confluentinc/cp-schema-registry:6.2.0
    restart: always
    container_name: registry-1
    depends_on:
      - kafka1
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry-1
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka1:19091
    ports:
      - 8085:8085
